### ISSUE TITLE
Annotation axioms with value:Individual become lists of attributes on a node

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/vfb-integration-api#2]
VFB_00055130 in KB

![image](https://user-images.githubusercontent.com/112839/61730641-b4ef4480-ad71-11e9-87dd-00e6b8c6b170.png)

in PDB - link to source is missing

![image](https://user-images.githubusercontent.com/112839/61730505-6cd02200-ad71-11e9-8aba-e50044aea1ac.png)

has_source axioms (with value  ["unknownX"]) appears on node:

```js
{
  "iri": "http://virtualflybrain.org/reports/VFB_00055130",
  "curie": "ns0:VFB_00055130",
  "short_form": "VFB_00055130",
  "sl": "VFB_00055130",
  "label": "VFB_00055130",
  "qsl": "VFB_00055130_ns0",
  "has_source_ns1": [
    "unknownX"
  ]
}```

**Comment by matentzn** [comment]
Fixed.
