### ISSUE TITLE
Some created by links appear wrong

### ISSUE THREAD

**Issue by matentzn** [VirtualFlyBrain/vfb-integration-api#3]
I dont know where these come from right now, but you can probably tell immediately (note missing h in IRI):

http://ts.p2.virtualflybrain.org/rdf4j-workbench/repositories/vfb/query?action=exec&queryLn=SPARQL&query=PREFIX%20%3A%20%3Chttp%3A%2F%2Fwww.test.com%2Fns%2Ftest%23%3E%0A%0ACONSTRUCT%20%7B%20%3Fx%20%3Fp%20%3Fy%20.%20%7D%0A%0AWHERE%20%7B%0A%20%20%3Fx%20%3Fp%20%3Fy%20.%0A%20%20FILTER(%3Fp%3D%3Cttp%3A%2F%2Fwww.geneontology.org%2Fformats%2FoboInOwl%23created_by%3E)%0A%7D%0A%0ALIMIT%20100&limit_query=100&infer=true&

**Comment by dosumis** [comment]
Oddity in VFB_ext.owl file.  Not sure how it got there, but easy to fix.

**Comment by dosumis** [comment]
Seems to have been fixed by pull (see link).

**Comment by matentzn** [comment]
Sorry still there; you probably hit an empty triplestore when you tested!

**Comment by matentzn** [comment]
http://ts.p2.virtualflybrain.org/rdf4j-workbench/repositories/vfb/query?action=exec&queryLn=SPARQL&query=PREFIX%20%3A%20%3Chttp%3A%2F%2Fwww.test.com%2Fns%2Ftest%23%3E%0A%0ACONSTRUCT%20%7B%20%3Fx%20%3Fp%20%3Fy%20.%20%7D%0A%0AWHERE%20%7B%0A%20%20%3Fx%20%3Fp%20%3Fy%20.%0A%20%20FILTER(%3Fp%3D%3Cttp%3A%2F%2Fwww.geneontology.org%2Fformats%2FoboInOwl%23created_by%3E)%0A%7D%0A%0ALIMIT%20100&limit_query=100&infer=true&
